[package]
name = "aero-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = { version = "0.6.18", features = ["multipart"] }
dirs = "5.0.1"
serde = "1.0.160"
tokio = { version = "1.28.0", features = ["full"] }
