version: '3'

services:
  app:
    image: rust:1.68.2-bullseye
    ports:
      - 3000:3000
    volumes:
      - .:/app
    tty: true

  # Admin console url is http://localhost:5984/_utils
  couch:
    image: couchdb:latest
    ports:
      - 5984:5984
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    volumes:
      - couch:/opt/couchdb/data

volumes:
  couch:
